SELECT
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
  ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES BS
  ON BS.BOOK_ID = B.BOOK_ID
WHERE BS.SALES_DATE >= '2022-01-01' AND
    BS.SALES_DATE < '2022-02-01'
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;