SELECT DISTINCT CART_ID
FROM CART_PRODUCTS T
WHERE CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE CART_ID = T.CART_ID
      AND NAME = 'Milk'
)
  AND CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE CART_ID = T.CART_ID
      AND NAME = 'Yogurt'
)
ORDER BY CART_ID ASC;