SELECT THIRD.ID
FROM ECOLI_DATA THIRD
JOIN (
    SELECT SECOND.ID
    FROM ECOLI_DATA SECOND
    JOIN (
        SELECT FIRST.ID
        FROM ECOLI_DATA FIRST
        WHERE PARENT_ID IS NULL
    ) FIRST
    ON SECOND.PARENT_ID = FIRST.ID
) SECOND
ON THIRD.PARENT_ID = SECOND.ID
ORDER BY THIRD.ID ASC;