# SELECT C.ID
# FROM ECOLI_DATA C
# JOIN ECOLI_DATA P ON C.PARENT_ID = P.ID
# JOIN ECOLI_DATA G ON P.PARENT_ID = G.ID
# WHERE G.PARENT_ID IS NULL
# ORDER BY C.ID ASC;

WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN G
      ON E.PARENT_ID = G.ID
)
SELECT ID FROM GEN G
WHERE G.GENERATION = 3
ORDER BY ID ASC;