SELECT 
    CAR.CAR_ID,
    CAR.CAR_TYPE,
    CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) DIV 100 * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
  ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
    WHERE HISTORY.CAR_ID = CAR.CAR_ID
      AND START_DATE <= '2022-11-30' 
      AND END_DATE >= '2022-11-01'
)
  AND PLAN.DURATION_TYPE = '30일 이상'
  AND CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) DIV 100 * 30 >= 500000
  AND CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) DIV 100 * 30 < 2000000
ORDER BY 
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;