SELECT 
    RI.REST_ID, RI.REST_NAME,
    RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS,
    R.SCORE
FROM REST_INFO RI
JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) R
ON RI.REST_ID = R.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS
ORDER BY SCORE DESC, RI.FAVORITES DESC;