SELECT
    OS.YEAR,
    OS.MONTH,
    UI.GENDER,
    COUNT(*) AS USERS
FROM USER_INFO UI
JOIN (
    SELECT DISTINCT 
        USER_ID, 
        YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    GROUP BY USER_ID, YEAR, MONTH
) OS
  ON UI.USER_ID = OS.USER_ID AND UI.GENDER IS NOT NULL
GROUP BY OS.YEAR, OS.MONTH, UI.GENDER
ORDER BY OS.YEAR, OS.MONTH, UI.GENDER;
