SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT UI.USER_ID) / UI.TOTAL, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
JOIN (
    SELECT USER_ID, COUNT(USER_ID) OVER () AS TOTAL
    FROM USER_INFO WHERE YEAR(JOINED) = 2021
) UI
  ON UI.USER_ID = OS.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY
    YEAR ASC,
    MONTH ASC;