WITH RECURSIVE GEN AS (
    SELECT ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, G.GEN+1
    FROM ECOLI_DATA E
    JOIN GEN G
      ON G.ID = E.PARENT_ID
)
SELECT 
    COUNT(*) AS COUNT,
    GEN.GEN AS GENERATION
FROM GEN
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA E
    WHERE E.PARENT_ID = GEN.ID
)
GROUP BY GEN.GEN
ORDER BY GEN.GEN ASC;