SELECT DISTINCT
    H.HISTORY_ID,
    C.DAILY_FEE * (100 - (
        CASE
            WHEN DURATION >= 90 
                THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN  WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭')
            WHEN DURATION >= 30 
                THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN  WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭')
            WHEN DURATION >= 7 
                THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN  WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭')
            ELSE 0
        END)) DIV 100 * H.DURATION AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT
        HISTORY_ID,
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE)+1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
) H
  ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON P.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC,
    H.HISTORY_ID DESC;