WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM HOURS
    WHERE HOUR < 23
)
SELECT H.HOUR, COUNT(T.ANIMAL_ID) AS COUNT
FROM HOURS H 
LEFT JOIN ANIMAL_OUTS T
  ON HOUR(T.DATETIME) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR; 