WITH SC AS (
    SELECT SUM(CODE) AS FE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
CROSS JOIN SC
WHERE (D.SKILL_CODE & SC.FE) > 0
ORDER BY ID ASC;