a = input()
b = input()
l = len(a)
for i in range(l): print('1' if a[i] == '1' and b[i] == '1' else '0', end='')
print()
for i in range(l): print('1' if a[i] == '1' or b[i] == '1' else '0', end='')
print()
for i in range(l): print('1' if a[i] != b[i] else '0', end='')
print()
for i in range(l): print('1' if a[i] == '0' else '0', end='')
print()
for i in range(l): print('1' if b[i] == '0' else '0', end='')
print()
