SELECT
    M.MEMBER_NAME, 
    R.REVIEW_TEXT,
    LEFT(R.REVIEW_DATE, 10) AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
  ON M.MEMBER_ID = R.MEMBER_ID
JOIN (
    SELECT
        MEMBER_ID,
        COUNT(*) AS COUNT,
        MAX(COUNT(*)) OVER () AS MAX_COUNT
    FROM 
        REST_REVIEW
    GROUP BY MEMBER_ID
) C
  ON M.MEMBER_ID = C.MEMBER_ID
WHERE C.COUNT = C.MAX_COUNT
ORDER BY
    R.REVIEW_DATE ASC,
    R.REVIEW_TEXT ASC;