WITH FILTERED AS (
    SELECT 
        EMP_NO,
        SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT
    HG.TOTAL_SCORE AS SCORE,
    HE.EMP_NO,
    HE.EMP_NAME,
    HE.POSITION,
    HE.EMAIL
FROM HR_EMPLOYEES HE
JOIN FILTERED HG
  ON HE.EMP_NO = HG.EMP_NO
WHERE HG.TOTAL_SCORE = (
    SELECT MAX(TOTAL_SCORE) AS MAX_SCORE
    FROM FILTERED
);