SELECT
    DEPT.DEPT_ID,
    DEPT.DEPT_NAME_EN,
    ROUND(AVG(EMP.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT DEPT
JOIN HR_EMPLOYEES EMP
  ON DEPT.DEPT_ID = EMP.DEPT_ID
GROUP BY DEPT.DEPT_ID, DEPT.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;