SELECT 
    F.CATEGORY,
    M.MAX_PRICE,
    F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) M
WHERE F.CATEGORY IN ('과자', '국', '김치', '식용유') AND
      F.CATEGORY = M.CATEGORY AND
      F.PRICE = M.MAX_PRICE
ORDER BY F.PRICE DESC;