SELECT 
    CASE 
        WHEN (D.SKILL_CODE & SC.PYTHON) = SC.PYTHON
         AND (D.SKILL_CODE & SC.FRONT_END) > 0
        THEN 'A'
        WHEN (D.SKILL_CODE & SC.C_SHARP) = SC.C_SHARP THEN 'B'
        WHEN (D.SKILL_CODE & SC.FRONT_END) > 0 THEN 'C'
        ELSE NULL
    END AS GRADE, 
    D.ID, D.EMAIL
FROM DEVELOPERS D
JOIN (
    SELECT 
        SUM(CASE WHEN NAME = 'Python' THEN CODE ELSE 0 END) AS PYTHON,
        SUM(CASE WHEN NAME = 'C#' THEN CODE ELSE 0 END) AS C_SHARP,
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONT_END
    FROM SKILLCODES
) SC
WHERE 
    CASE 
        WHEN (D.SKILL_CODE & SC.PYTHON) = SC.PYTHON
         AND (D.SKILL_CODE & SC.FRONT_END) > 0
        THEN 'A'
        WHEN (D.SKILL_CODE & SC.C_SHARP) = SC.C_SHARP THEN 'B'
        WHEN (D.SKILL_CODE & SC.FRONT_END) > 0 THEN 'C'
        ELSE NULL
    END IS NOT NULL
ORDER BY GRADE ASC, ID ASC;